# Generated by Django 4.1.7 on 2023-04-01 10:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0004_blogproject_delete_project'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BlogProject',
            new_name='Project',
        ),
    ]
